export type FrankLabModule = 'holst' | 'kley' | 'plastinka' | 'volna' | 'c2pa';
export type AuthHeader = 'Authorization' | 'X-API-Key';
export type HttpMethod = 'GET' | 'POST';
export type ResponseEnvelope = 'successData' | 'codeData';

export interface EndpointDefinition {
	key: string;
	module: FrankLabModule;
	operation: string;
	routeFamily: string;
	method: HttpMethod;
	path: string;
	authHeader: AuthHeader;
	guard: string;
	requestShape: string;
	responseEnvelope: ResponseEnvelope;
	statusPath: string;
	terminalStatuses: readonly string[];
	outputExtractor: string;
	costFields: readonly string[];
	redactionFields: readonly string[];
}

export const SUCCESS_STATUSES = ['completed', 'success', 'succeed', 'succeeded', 'done'] as const;
export const FAILURE_STATUSES = ['failed', 'fail', 'error', 'refunded', 'cancelled'] as const;
export const ACTIVE_STATUSES = ['queued', 'processing'] as const;
export const TERMINAL_STATUSES = [...SUCCESS_STATUSES, ...FAILURE_STATUSES] as const;

const COST_FIELDS = ['final_cost_franks', 'cost_currency', 'cost_status', 'cost_unit'] as const;
const BEARER_REDACTION = ['request.headers.Authorization', 'body.apiKey', 'body.token'] as const;
const API_KEY_REDACTION = ['request.headers.X-API-Key', 'body.apiKey', 'body.token'] as const;
const JOB_OUTPUT = 'job-result';
const PROFILE_OUTPUT = 'profile-result';
const PROFILE_OPTIONS_OUTPUT = 'profile-options';
const LIST_OUTPUT = 'list-result';
const VOLNA_OUTPUT = 'volna-result';

function endpoint(definition: EndpointDefinition): EndpointDefinition {
	return definition;
}

export const ENDPOINT_REGISTRY: Record<string, EndpointDefinition> = {
	'holst.submitImage': endpoint({
		key: 'holst.submitImage',
		module: 'holst',
		operation: 'submitImage',
		routeFamily: 'franklab-partner-jobs',
		method: 'POST',
		path: '/franklab/jobs/image',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'imageUrl plus image operation or steps',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'holst.getStatus': endpoint({
		key: 'holst.getStatus',
		module: 'holst',
		operation: 'getStatus',
		routeFamily: 'franklab-partner-jobs',
		method: 'GET',
		path: '/franklab/jobs/:jobId',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'jobId path parameter',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'kley.montage': endpoint({
		key: 'kley.montage',
		module: 'kley',
		operation: 'montage',
		routeFamily: 'franklab-partner-jobs',
		method: 'POST',
		path: '/franklab/jobs/montage',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'montage operation payload',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'kley.videoSpeed': endpoint({
		key: 'kley.videoSpeed',
		module: 'kley',
		operation: 'videoSpeed',
		routeFamily: 'franklab-partner-jobs',
		method: 'POST',
		path: '/franklab/jobs/video-speed',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'videoUrl and speed',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'kley.subtitles': endpoint({
		key: 'kley.subtitles',
		module: 'kley',
		operation: 'subtitles',
		routeFamily: 'franklab-partner-jobs',
		method: 'POST',
		path: '/franklab/jobs/subtitles',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'subtitle rendering payload',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'kley.overlay': endpoint({
		key: 'kley.overlay',
		module: 'kley',
		operation: 'overlay',
		routeFamily: 'franklab-partner-jobs',
		method: 'POST',
		path: '/franklab/jobs/overlay',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'overlay payload',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'kley.getStatus': endpoint({
		key: 'kley.getStatus',
		module: 'kley',
		operation: 'getStatus',
		routeFamily: 'franklab-partner-jobs',
		method: 'GET',
		path: '/franklab/jobs/:jobId',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'jobId path parameter',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'plastinka.processAudio': endpoint({
		key: 'plastinka.processAudio',
		module: 'plastinka',
		operation: 'processAudio',
		routeFamily: 'franklab-partner-jobs',
		method: 'POST',
		path: '/franklab/jobs/audio',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'audio processing payload',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'plastinka.saveSample': endpoint({
		key: 'plastinka.saveSample',
		module: 'plastinka',
		operation: 'saveSample',
		routeFamily: 'franklab-audio-samples',
		method: 'POST',
		path: '/franklab/audio-samples',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'sample label and URL-only source fields',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: PROFILE_OUTPUT,
		costFields: [],
		redactionFields: BEARER_REDACTION,
	}),
	'plastinka.listSamples': endpoint({
		key: 'plastinka.listSamples',
		module: 'plastinka',
		operation: 'listSamples',
		routeFamily: 'franklab-audio-samples',
		method: 'GET',
		path: '/franklab/integrations/text-sticker/audio-samples',
		authHeader: 'Authorization',
		guard: 'ApiKeyGuard',
		requestShape: 'none',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: LIST_OUTPUT,
		costFields: [],
		redactionFields: BEARER_REDACTION,
	}),
	'plastinka.getStatus': endpoint({
		key: 'plastinka.getStatus',
		module: 'plastinka',
		operation: 'getStatus',
		routeFamily: 'franklab-partner-jobs',
		method: 'GET',
		path: '/franklab/jobs/:jobId',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'jobId path parameter',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: JOB_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: BEARER_REDACTION,
	}),
	'volna.textToSpeech': endpoint({
		key: 'volna.textToSpeech',
		module: 'volna',
		operation: 'textToSpeech',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/tts',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'text and voice fields',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.textToDialogue': endpoint({
		key: 'volna.textToDialogue',
		module: 'volna',
		operation: 'textToDialogue',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/tts',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'dialogue text and voice fields',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.textToSpeechTurbo': endpoint({
		key: 'volna.textToSpeechTurbo',
		module: 'volna',
		operation: 'textToSpeechTurbo',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/tts',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'text and Flash TTS voice fields',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.googleTts': endpoint({
		key: 'volna.googleTts',
		module: 'volna',
		operation: 'googleTts',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/tts',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'Google Gemini TTS payload',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.transcribe': endpoint({
		key: 'volna.transcribe',
		module: 'volna',
		operation: 'transcribe',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/transcribe',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'audio URL and transcription options',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.soundEffect': endpoint({
		key: 'volna.soundEffect',
		module: 'volna',
		operation: 'soundEffect',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/sound-effect',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'sound effect prompt payload',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.audioIsolation': endpoint({
		key: 'volna.audioIsolation',
		module: 'volna',
		operation: 'audioIsolation',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/audio-isolation',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'audio URL',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.voiceClone': endpoint({
		key: 'volna.voiceClone',
		module: 'volna',
		operation: 'voiceClone',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/voices/clone',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard + KusokApiKeyGuard',
		requestShape: 'voice clone URL-only payload',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.voiceDesign': endpoint({
		key: 'volna.voiceDesign',
		module: 'volna',
		operation: 'voiceDesign',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/voices/design',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard + KusokApiKeyGuard',
		requestShape: 'voice design payload',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.voiceDesignSave': endpoint({
		key: 'volna.voiceDesignSave',
		module: 'volna',
		operation: 'voiceDesignSave',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/voices/design/save',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard + KusokApiKeyGuard',
		requestShape: 'voice design save payload',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.dubbing': endpoint({
		key: 'volna.dubbing',
		module: 'volna',
		operation: 'dubbing',
		routeFamily: 'franklab-volna',
		method: 'POST',
		path: '/make/volna/dubbing',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'dubbing payload',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.listVoices': endpoint({
		key: 'volna.listVoices',
		module: 'volna',
		operation: 'listVoices',
		routeFamily: 'franklab-volna',
		method: 'GET',
		path: '/make/volna/voices',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'none',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: LIST_OUTPUT,
		costFields: [],
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.listModels': endpoint({
		key: 'volna.listModels',
		module: 'volna',
		operation: 'listModels',
		routeFamily: 'franklab-volna',
		method: 'GET',
		path: '/make/volna/models',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'none',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: LIST_OUTPUT,
		costFields: [],
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.usage': endpoint({
		key: 'volna.usage',
		module: 'volna',
		operation: 'usage',
		routeFamily: 'franklab-volna',
		method: 'GET',
		path: '/make/volna/usage',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard + KusokApiKeyGuard',
		requestShape: 'none',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: PROFILE_OUTPUT,
		costFields: [],
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.getTask': endpoint({
		key: 'volna.getTask',
		module: 'volna',
		operation: 'getTask',
		routeFamily: 'franklab-volna',
		method: 'GET',
		path: '/make/volna/tasks/:taskId',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'taskId path parameter',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'volna.getDubbing': endpoint({
		key: 'volna.getDubbing',
		module: 'volna',
		operation: 'getDubbing',
		routeFamily: 'franklab-volna',
		method: 'GET',
		path: '/make/volna/dubbing/:dubbingId',
		authHeader: 'X-API-Key',
		guard: 'ApiKeyGuard',
		requestShape: 'dubbingId path parameter',
		responseEnvelope: 'codeData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: VOLNA_OUTPUT,
		costFields: COST_FIELDS,
		redactionFields: API_KEY_REDACTION,
	}),
	'c2pa.listProfiles': endpoint({
		key: 'c2pa.listProfiles',
		module: 'c2pa',
		operation: 'listProfiles',
		routeFamily: 'franklab-c2pa-signer-profiles',
		method: 'GET',
		path: '/make/c2pa/signer-profiles',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'none',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: LIST_OUTPUT,
		costFields: [],
		redactionFields: BEARER_REDACTION,
	}),
	'c2pa.profileOptions': endpoint({
		key: 'c2pa.profileOptions',
		module: 'c2pa',
		operation: 'profileOptions',
		routeFamily: 'franklab-c2pa-signer-profiles',
		method: 'GET',
		path: '/make/c2pa/signer-profiles',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'none',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: PROFILE_OPTIONS_OUTPUT,
		costFields: [],
		redactionFields: BEARER_REDACTION,
	}),
	'c2pa.generateSelfSigned': endpoint({
		key: 'c2pa.generateSelfSigned',
		module: 'c2pa',
		operation: 'generateSelfSigned',
		routeFamily: 'franklab-c2pa-signer-profiles',
		method: 'POST',
		path: '/make/c2pa/signer-profiles',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'action and label',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: PROFILE_OUTPUT,
		costFields: [],
		redactionFields: BEARER_REDACTION,
	}),
	'c2pa.revokeProfile': endpoint({
		key: 'c2pa.revokeProfile',
		module: 'c2pa',
		operation: 'revokeProfile',
		routeFamily: 'franklab-c2pa-signer-profiles',
		method: 'POST',
		path: '/make/c2pa/signer-profiles/:profileId/revoke',
		authHeader: 'Authorization',
		guard: 'PartnerSessionOrApiKeyGuard',
		requestShape: 'profileId path parameter',
		responseEnvelope: 'successData',
		statusPath: 'data.status',
		terminalStatuses: TERMINAL_STATUSES,
		outputExtractor: PROFILE_OUTPUT,
		costFields: [],
		redactionFields: BEARER_REDACTION,
	}),
};

export const MODULE_OPERATIONS: Record<FrankLabModule, string[]> = {
	holst: ['submitImage', 'getStatus'],
	kley: ['montage', 'videoSpeed', 'subtitles', 'overlay', 'getStatus'],
	plastinka: ['processAudio', 'saveSample', 'listSamples', 'getStatus'],
	volna: [
		'textToSpeech',
		'textToDialogue',
		'textToSpeechTurbo',
		'googleTts',
		'transcribe',
		'soundEffect',
		'audioIsolation',
		'voiceClone',
		'voiceDesign',
		'voiceDesignSave',
		'dubbing',
		'listVoices',
		'listModels',
		'usage',
		'getTask',
		'getDubbing',
	],
	c2pa: ['listProfiles', 'profileOptions', 'generateSelfSigned', 'revokeProfile'],
};

export function getEndpoint(key: string): EndpointDefinition {
	const endpointDefinition = ENDPOINT_REGISTRY[key];
	if (!endpointDefinition) {
		throw new Error(`Unsupported FrankLab operation: ${key}`);
	}
	return endpointDefinition;
}

export function keyFor(moduleName: FrankLabModule, operation: string): string {
	return `${moduleName}.${operation}`;
}
