import type { IExecuteFunctions, INodeType, INodeTypeDescription } from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';
import { executeFrankLabModule, jobIdProperty, payloadProperty, waitProperty } from '../shared/node-utils';

export class FrankLabVolna implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'FrankLab VOLNA',
		name: 'frankLabVolna',
		icon: 'file:volna.svg',
		group: ['transform'],
		version: 1,
		description: 'Generate and process speech, voice, dubbing, and audio with FrankLab VOLNA.',
		defaults: {
			name: 'FrankLab VOLNA',
		},
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		credentials: [
			{
				name: 'frankLabApi',
				required: true,
			},
		],
		usableAsTool: true,
		properties: [
			{
				displayName: 'Resource',
				name: 'resource',
				type: 'options',
				noDataExpression: true,
				default: 'speech',
				options: [
					{ name: 'Audio', value: 'audio' },
					{ name: 'Dubbing', value: 'dubbing' },
					{ name: 'Model', value: 'model' },
					{ name: 'Speech', value: 'speech' },
					{ name: 'Task', value: 'task' },
					{ name: 'Usage', value: 'usage' },
					{ name: 'Voice', value: 'voice' },
				],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'audioIsolation',
				displayOptions: { show: { resource: ['audio'] } },
				options: [
					{ name: 'Audio Isolation', value: 'audioIsolation', action: 'Audio isolation an audio' },
					{ name: 'Sound Effect', value: 'soundEffect', action: 'Sound effect an audio' },
				],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'dubbing',
				displayOptions: { show: { resource: ['dubbing'] } },
				options: [
					{ name: 'Dubbing', value: 'dubbing', action: 'Create a dubbing job' },
					{ name: 'Get Dubbing Status', value: 'getDubbing', action: 'Get dubbing status' },
				],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'listModels',
				displayOptions: { show: { resource: ['model'] } },
				options: [{ name: 'List Models', value: 'listModels', action: 'List models a model' }],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'textToSpeech',
				displayOptions: { show: { resource: ['speech'] } },
				options: [
					{ name: 'Google 3.1 TTS', value: 'googleTts', action: 'Generate google tts audio' },
					{ name: 'Speech to Text', value: 'transcribe', action: 'Speech to text a speech' },
					{ name: 'Text to Dialogue', value: 'textToDialogue', action: 'Generate dialogue audio' },
					{ name: 'Text to Speech', value: 'textToSpeech', action: 'Text to speech a speech' },
					{ name: 'Text to Speech Turbo', value: 'textToSpeechTurbo', action: 'Generate turbo speech audio' },
				],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'getTask',
				displayOptions: { show: { resource: ['task'] } },
				options: [{ name: 'Get Task', value: 'getTask', action: 'Get task a task' }],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'usage',
				displayOptions: { show: { resource: ['usage'] } },
				options: [{ name: 'Usage', value: 'usage', action: 'Usage a usage' }],
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				default: 'listVoices',
				displayOptions: { show: { resource: ['voice'] } },
				options: [
					{ name: 'List Voices', value: 'listVoices', action: 'List voices a voice' },
					{ name: 'Save Designed Voice', value: 'voiceDesignSave', action: 'Save designed voice a voice' },
					{ name: 'Voice Clone', value: 'voiceClone', action: 'Voice clone a voice' },
					{ name: 'Voice Design', value: 'voiceDesign', action: 'Voice design a voice' },
				],
			},
			{
				displayName: 'Text',
				name: 'text',
				type: 'string',
				default: '',
				typeOptions: { rows: 4 },
				displayOptions: { show: { operation: ['textToSpeech', 'textToDialogue', 'textToSpeechTurbo', 'googleTts', 'soundEffect', 'voiceDesign'] } },
			},
			{
				displayName: 'Voice ID',
				name: 'voice_id',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['textToSpeech', 'textToDialogue', 'textToSpeechTurbo'] } },
			},
			{
				displayName: 'Second Voice ID',
				name: 'voice_id_2',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['textToDialogue'] } },
			},
			{
				displayName: 'Google TTS Mode',
				name: 'google_tts_mode',
				type: 'options',
				default: 'single',
				displayOptions: { show: { operation: ['googleTts'] } },
				options: [
					{ name: 'Single Speaker', value: 'single' },
					{ name: 'Two Speakers', value: 'multi' },
				],
			},
			{
				displayName: 'Google Voice Name',
				name: 'google_voice_name',
				type: 'string',
				default: 'Kore',
				displayOptions: { show: { operation: ['googleTts'] } },
			},
			{
				displayName: 'Speaker 1 Name',
				name: 'speaker_1_name',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['googleTts'] } },
			},
			{
				displayName: 'Speaker 1 Voice',
				name: 'speaker_1_voice',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['googleTts'] } },
			},
			{
				displayName: 'Speaker 2 Name',
				name: 'speaker_2_name',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['googleTts'] } },
			},
			{
				displayName: 'Speaker 2 Voice',
				name: 'speaker_2_voice',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['googleTts'] } },
			},
			{
				displayName: 'Style Prompt',
				name: 'style_prompt',
				type: 'string',
				default: '',
				typeOptions: { rows: 3 },
				displayOptions: { show: { operation: ['googleTts'] } },
			},
			{
				displayName: 'Audio URL',
				name: 'audio_url',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['transcribe', 'audioIsolation'] } },
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['voiceClone', 'dubbing'] } },
			},
			{
				displayName: 'Source URL',
				name: 'source_url',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['dubbing'] } },
			},
			{
				displayName: 'Target Language',
				name: 'target_lang',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['dubbing'] } },
			},
			{
				displayName: 'Source Language',
				name: 'source_lang',
				type: 'string',
				default: '',
				displayOptions: { show: { operation: ['dubbing'] } },
			},
			jobIdProperty,
			payloadProperty,
			waitProperty,
		],
	};

	async execute(this: IExecuteFunctions) {
		return executeFrankLabModule(this, 'volna', { default: 'getTask', dubbing: 'getDubbing' });
	}
}
